name = "Piekarnia Modpack"
author = "Jakub"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bf6a494cb7c4c971bc115280d261eff429b7c3b7dbfb8790e1879a57d7e50b5"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
