name = "Piekarnia Modpack"
author = "Jakub"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e86dc202f4a18e636e9bc80e635853b5db18d919c29fc3b36700c3faecb4641"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
