name = "Piekarnia Modpack"
author = "Jakub"
version = "3.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a305538370995603fcfa0e6f2e7d11c53301b92dc917920336edb27a87470885"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
